### ISSUE TITLE
z-index scale

### ISSUE THREAD

**Issue by jthrilly** [codaco/Network-Canvas-UI#56]
We have no standard z-index approach across our apps. The following is a proposal adapted loosely from what Medium and others seem to do.

``` CSS

/* 
  The following are private variables, not designed to be referenced 
  directly in component code, but instead designed to be "linked" to 
  our actual use cases.
*/

:root {
  --z-index-1: 1;
  --z-index-2: 2;
  --z-index-3: 3;
  --z-index-4: 4;
  --z-index-5: 5;
  --z-index-6: 6;
  --z-index-7: 7;
  --z-index-8: 8;
  --z-index-9: 9;
  --z-index-10: 10;
}

/*  
  Here we have our actual use cases, grouped by the levels above.

  These are implemented within each app, so that apps can provide 
  shortcuts to the levels meaningful to them. Below is for NC.
*/ 


:root {
  /* Level 1 */
  --z-background: var(--z-index-1);

  /* Level 2 */
  --z-stage: var(--z-index-2);
  --z-edge: var(--z-index-2);
  --z-node: var(--z-index-2);

  /* Level 3 */
  --z-panel:  var(--z-index-3);
  --z-prompt:  var(--z-index-3);

  /* Level 4 */
  --z-global-ui:  var(--z-index-4);
  --z-navigation:  var(--z-index-4);
  --z-menu:  var(--z-index-4);

  /* Level 5 */
  --z-tooltip:  var(--z-index-5);
  --z-toast-notification:  var(--z-index-5);

  /* Level 6 */
  --z-fullscreen-overlay:  var(--z-index-6);
  --z-dialog:  var(--z-index-6);

  /* Level 10 */
  // Reserved for development stuff that must always be visible
  --z-dev:  var(--z-index-10);

}

/* 
  Use within a component
*/

.background {
  z-index: var(--z-background);
}

```

**Comment by jthrilly** [comment]
I'd appreciate any input @wwqrd @bryfox @rebeccamadsen

**Comment by bryfox** [comment]
Looks good; minor questions/comments:

1. Does explicitly setting a positive index on background imply that all components should also explicitly set z-indexes? That feels heavier than needed — most things can just use default — but maybe I'm just not used to that pattern.
2. Using multiples of 10 (10-100) instead of 1-10 would allow more flexibility during development, especially on Server where a lot of the UI (e.g. reports/dashboards) isn't yet well-defined. But it's not a big deal.
3. CSS custom properties vs SCSS variables... I used the former in Server, but wonder if using the latter might be a good thing (to make overriding 'harder'). I think z-index problems often come up in specific situations revealed by group testing.
4. I noticed we turned off the linter rule against CSS comments & you're using them here. Is there a reason for using them (vs sass-style)?

**Comment by wwqrd** [comment]
> Using multiples of 10 (10-100) instead of 1-10 would allow more flexibility during development, especially on Server where a lot of the UI (e.g. reports/dashboards) isn't yet well-defined. But it's not a big deal.

This functionality is needed in Architect too, where a single component uses multiple z-index to fine tune ordering of sub components.

Failing that we could leverage stacking context: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

**Comment by jthrilly** [comment]
> Does explicitly setting a positive index on background imply that all components should also explicitly set z-indexes? That feels heavier than needed — most things can just use default — but maybe I'm just not used to that pattern.

If you were referring to the example assignment to .background, that was probably a poorly chosen use-case. I can see a use for setting z-index unambiguously, though.



> Using multiples of 10 (10-100) instead of 1-10 would allow more flexibility during development, especially on Server where a lot of the UI (e.g. reports/dashboards) isn't yet well-defined. But it's not a big deal.

I did originally do it that way, but then I decided that using single incrementing integers would force us to think more clearly about z-index, instead of just incrementing it as a "get out of jail". I didn't want to end up with 101, 102, 103, etc. when the underlying issue is elsewhere. 

@wwqrd as you suggest, I had imagined that within component z-index could be handled with stacking context. There's actually a way of implementing global z-index and stacking context using SCSS, but I wanted to use CSS variables.

> CSS custom properties vs SCSS variables... I used the former in Server, but wonder if using the latter might be a good thing (to make overriding 'harder'). I think z-index problems often come up in specific situations revealed by group testing.

I'm not sure I see the advantage for making overriding harder, or actually how implementing in SCSS would actually do that. In either case, wouldn't each app have a single location for defining these z-index layers?

> I noticed we turned off the linter rule against CSS comments & you're using them here. Is there a reason for using them (vs sass-style)?

Only that I prefer them, really, and go them instinctively. I think they are stripped out in the production bundle (or should be...) so I didn't really understand the purpose of the linting rule. Do you feel strongly about using the other comment style?

**Comment by bryfox** [comment]
> Do you feel strongly about using the other comment style?

No, just curious. Looks good.

> making overriding harder

Sorry, I meant to say overriding by end users (post-build). We switched to custom props to make overrides (of colors, etc.) easier in that case, so I've been thinking of that as akin to a public interface. I wasn't sure if we wanted to expose indexing in the same way.

**Comment by wwqrd** [comment]
One thing I'd like to change about this proposed feature is more general naming that defines roles rather than specific components, like 'node', and then only have one name for each of those.

eg.

```css
:root {
  /* Level 1 */
  --z-background: var(--z-index-1);

  /* Level 2 */
  --z-default: var(--z-index-2);

  /* Level 3 */
  --z-panel:  var(--z-index-3);

  /* Level 4 */
  --z-chrome:  var(--z-index-4);

  /* Level 5 */
  --z-tooltip:  var(--z-index-5);

  /* Level 6 */
  --z-modal:  var(--z-index-6);

  /* Level 10 */
  --z-dev:  var(--z-index-10);

}
```
